name: Update Index

on:
  pull_request:
  workflow_run:
    workflows:
      - "YaSpeller All"
    branches:
      - main
    types:
      - completed

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Установка ключа для пользователя
        run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "${{ secrets.DEPLOY_KEY }}" > "$HOME/.ssh/doka_deploy"
          chmod 600 "$HOME/.ssh/doka_deploy"
      - name: Публикация поискового индекса
        run: |
          npm install natural linkedom html-escaper markdown-it yaml-cat --global
          npm link natural linkedom html-escaper markdown-it
          yaml-cat -f json **/**/index.md -o search-meta.json
          node .github/scripts/search-index.js
          rsync -e \"ssh -i $HOME/.ssh/doka_deploy -o StrictHostKeyChecking=no\" --archive --progress --compress search-* deploy@doka.guide:/web/sites/search.doka.guide/www/
